import { Product, Category } from '@/types';

export const categories: Category[] = [
  {
    id: 'laptops',
    name: 'Ordinateurs Portables',
    icon: '💻',
    description: 'Laptops gaming et bureautique',
    productCount: 3,
  },
  {
    id: 'accessories',
    name: 'Accessoires PC',
    icon: '⌨️',
    description: 'Claviers, souris et accessoires',
    productCount: 3,
  },
  {
    id: 'storage',
    name: 'Stockage',
    icon: '💾',
    description: 'SSD, disques durs et clés USB',
    productCount: 3,
  },
  {
    id: 'audio',
    name: 'Audio',
    icon: '🎧',
    description: 'Casques et écouteurs',
    productCount: 3,
  },
  {
    id: 'monitors',
    name: 'Écrans',
    icon: '🖥️',
    description: 'Moniteurs gaming et bureautique',
    productCount: 3,
  },
  {
    id: 'networking',
    name: 'Réseau',
    icon: '📡',
    description: 'Routeurs, adaptateurs WiFi',
    productCount: 3,
  },
];

export const products: Product[] = [
  // LAPTOPS - 3 produits
  {
    id: 'laptop-1',
    name: 'PC Portable 15.6" Intel Core i7 16Go RAM',
    description: 'Ordinateur portable haute performance pour le gaming et le travail. Écran FHD, SSD 512Go, carte graphique dédiée.',
    category: 'laptops',
    price: 549.99,
    originalPrice: 899.99,
    discount: 39,
    rating: 4.7,
    reviews: 2847,
    image: 'https://via.placeholder.com/400x300/1e40af/ffffff?text=Laptop+i7',
    images: [
      'https://via.placeholder.com/400x300/1e40af/ffffff?text=Laptop+i7',
      'https://via.placeholder.com/400x300/2563eb/ffffff?text=Laptop+Side',
      'https://via.placeholder.com/400x300/3b82f6/ffffff?text=Laptop+Open',
    ],
    stock: 45,
    aliexpressUrl: '#',
    features: [
      'Processeur Intel Core i7 11ème génération',
      '16Go RAM DDR4',
      'SSD 512Go NVMe',
      'Écran 15.6" Full HD IPS',
      'Carte graphique NVIDIA GTX',
      'Batterie longue durée 8h',
    ],
    specifications: {
      'Processeur': 'Intel Core i7-1165G7',
      'Mémoire': '16Go DDR4',
      'Stockage': '512Go SSD NVMe',
      'Écran': '15.6" FHD IPS 1920x1080',
      'GPU': 'NVIDIA GeForce GTX 1650',
      'Système': 'Windows 11 Pro',
      'Batterie': '56Wh (jusqu\'à 8h)',
      'Poids': '1.8 kg',
    },
  },
  {
    id: 'laptop-2',
    name: 'Laptop Gaming 17" AMD Ryzen 7 32Go',
    description: 'PC Gamer professionnel avec écran 144Hz, RGB et refroidissement avancé. Parfait pour gaming et création de contenu.',
    category: 'laptops',
    price: 899.99,
    originalPrice: 1299.99,
    discount: 31,
    rating: 4.8,
    reviews: 1523,
    image: 'https://via.placeholder.com/400x300/dc2626/ffffff?text=Gaming+Laptop',
    images: [
      'https://via.placeholder.com/400x300/dc2626/ffffff?text=Gaming+Laptop',
      'https://via.placeholder.com/400x300/ef4444/ffffff?text=RGB+Keyboard',
    ],
    stock: 23,
    aliexpressUrl: '#',
    features: [
      'AMD Ryzen 7 5800H',
      '32Go RAM DDR4 3200MHz',
      'SSD 1To + HDD 1To',
      'Écran 17.3" 144Hz',
      'RTX 3060 6Go',
      'Clavier RGB mécanique',
    ],
    specifications: {
      'Processeur': 'AMD Ryzen 7 5800H',
      'Mémoire': '32Go DDR4 3200MHz',
      'Stockage': '1To SSD + 1To HDD',
      'Écran': '17.3" FHD 144Hz',
      'GPU': 'NVIDIA RTX 3060 6Go',
      'Refroidissement': 'Double ventilateur',
      'Poids': '2.5 kg',
    },
  },
  {
    id: 'laptop-3',
    name: 'Ultrabook 14" Intel i5 8Go Ultra Léger',
    description: 'Ultraportable élégant et léger pour les professionnels mobiles. Design premium en aluminium.',
    category: 'laptops',
    price: 399.99,
    originalPrice: 649.99,
    discount: 38,
    rating: 4.6,
    reviews: 3214,
    image: 'https://via.placeholder.com/400x300/6366f1/ffffff?text=Ultrabook',
    images: [
      'https://via.placeholder.com/400x300/6366f1/ffffff?text=Ultrabook',
    ],
    stock: 67,
    aliexpressUrl: '#',
    features: [
      'Intel Core i5 1135G7',
      '8Go RAM',
      'SSD 256Go',
      'Écran 14" Full HD',
      'Design ultra fin 1.3kg',
      'Autonomie 10 heures',
    ],
    specifications: {
      'Processeur': 'Intel Core i5-1135G7',
      'Mémoire': '8Go DDR4',
      'Stockage': '256Go SSD',
      'Écran': '14" FHD IPS',
      'Châssis': 'Aluminium',
      'Poids': '1.3 kg',
      'Batterie': '10 heures',
    },
  },

  // ACCESSORIES - 3 produits
  {
    id: 'keyboard-1',
    name: 'Clavier Mécanique RGB Gaming 104 Touches',
    description: 'Clavier gaming mécanique avec switches bleus, rétroéclairage RGB personnalisable et repose-poignets.',
    category: 'accessories',
    price: 45.99,
    originalPrice: 89.99,
    discount: 49,
    rating: 4.8,
    reviews: 5632,
    image: 'https://via.placeholder.com/400x300/8b5cf6/ffffff?text=RGB+Keyboard',
    images: [
      'https://via.placeholder.com/400x300/8b5cf6/ffffff?text=RGB+Keyboard',
    ],
    stock: 156,
    aliexpressUrl: '#',
    features: [
      'Switches mécaniques bleus',
      'RGB 16.8 millions de couleurs',
      'Anti-ghosting 104 touches',
      'Repose-poignets amovible',
      'Câble tressé',
      'Compatible Windows/Mac',
    ],
    specifications: {
      'Type': 'Mécanique',
      'Switches': 'Bleus tactiles',
      'Touches': '104',
      'Rétroéclairage': 'RGB',
      'Connexion': 'USB Type-C',
      'Longueur câble': '1.8m',
    },
  },
  {
    id: 'mouse-1',
    name: 'Souris Gaming Sans Fil 16000 DPI RGB',
    description: 'Souris ergonomique professionnelle avec capteur optique haute précision et 7 boutons programmables.',
    category: 'accessories',
    price: 29.99,
    originalPrice: 69.99,
    discount: 57,
    rating: 4.7,
    reviews: 4521,
    image: 'https://via.placeholder.com/400x300/10b981/ffffff?text=Gaming+Mouse',
    images: [
      'https://via.placeholder.com/400x300/10b981/ffffff?text=Gaming+Mouse',
    ],
    stock: 234,
    aliexpressUrl: '#',
    features: [
      'Capteur 16000 DPI',
      '7 boutons programmables',
      'Sans fil 2.4GHz',
      'Batterie rechargeable',
      'RGB personnalisable',
      'Poids réglable',
    ],
    specifications: {
      'DPI': 'Jusqu\'à 16000',
      'Boutons': '7 programmables',
      'Connexion': '2.4GHz sans fil',
      'Batterie': '750mAh (70h)',
      'Poids': '95g (réglable)',
      'Compatibilité': 'Windows/Mac/Linux',
    },
  },
  {
    id: 'webcam-1',
    name: 'Webcam 4K Ultra HD Autofocus Microphone',
    description: 'Caméra web professionnelle 4K avec autofocus, micro stéréo et correction lumière pour streaming et visio.',
    category: 'accessories',
    price: 39.99,
    originalPrice: 89.99,
    discount: 56,
    rating: 4.6,
    reviews: 2134,
    image: 'https://via.placeholder.com/400x300/f59e0b/ffffff?text=4K+Webcam',
    images: [
      'https://via.placeholder.com/400x300/f59e0b/ffffff?text=4K+Webcam',
    ],
    stock: 89,
    aliexpressUrl: '#',
    features: [
      'Résolution 4K 3840x2160',
      'Autofocus automatique',
      'Microphone stéréo intégré',
      'Correction lumière faible',
      'Angle de vue 90°',
      'Compatible toutes plateformes',
    ],
    specifications: {
      'Résolution': '4K 3840x2160 @ 30fps',
      'Capteur': '8MP Sony',
      'Microphone': 'Stéréo',
      'Angle': '90°',
      'Connexion': 'USB 3.0',
      'Compatibilité': 'Windows/Mac/Linux',
    },
  },

  // STORAGE - 3 produits
  {
    id: 'ssd-1',
    name: 'SSD NVMe M.2 1To PCIe 4.0 7000 MB/s',
    description: 'Disque SSD ultra rapide dernière génération pour un démarrage et des transferts instantanés.',
    category: 'storage',
    price: 79.99,
    originalPrice: 149.99,
    discount: 47,
    rating: 4.9,
    reviews: 3847,
    image: 'https://via.placeholder.com/400x300/ec4899/ffffff?text=NVMe+SSD+1TB',
    images: [
      'https://via.placeholder.com/400x300/ec4899/ffffff?text=NVMe+SSD+1TB',
    ],
    stock: 178,
    aliexpressUrl: '#',
    features: [
      'Vitesse lecture 7000 MB/s',
      'Vitesse écriture 5000 MB/s',
      'Interface PCIe 4.0 x4',
      'Format M.2 2280',
      'Technologie TLC 3D NAND',
      'Garantie 5 ans',
    ],
    specifications: {
      'Capacité': '1To',
      'Interface': 'PCIe 4.0 x4 NVMe',
      'Format': 'M.2 2280',
      'Lecture': 'Jusqu\'à 7000 MB/s',
      'Écriture': 'Jusqu\'à 5000 MB/s',
      'NAND': 'TLC 3D',
      'Garantie': '5 ans',
    },
  },
  {
    id: 'usb-1',
    name: 'Clé USB 3.2 256Go Ultra Rapide Métal',
    description: 'Clé USB haute capacité en aluminium avec vitesses USB 3.2 Gen 2 pour transferts rapides.',
    category: 'storage',
    price: 19.99,
    originalPrice: 49.99,
    discount: 60,
    rating: 4.7,
    reviews: 6241,
    image: 'https://via.placeholder.com/400x300/06b6d4/ffffff?text=USB+256GB',
    images: [
      'https://via.placeholder.com/400x300/06b6d4/ffffff?text=USB+256GB',
    ],
    stock: 342,
    aliexpressUrl: '#',
    features: [
      'Capacité 256Go',
      'USB 3.2 Gen 2',
      'Vitesse jusqu\'à 400 MB/s',
      'Boîtier aluminium',
      'Capuchon rotatif',
      'Compatible tous OS',
    ],
    specifications: {
      'Capacité': '256Go',
      'Interface': 'USB 3.2 Gen 2',
      'Lecture': 'Jusqu\'à 420 MB/s',
      'Écriture': 'Jusqu\'à 380 MB/s',
      'Matériau': 'Aluminium',
      'Dimensions': '60 x 19 x 9 mm',
    },
  },
  {
    id: 'hdd-1',
    name: 'Disque Dur Externe 2To USB 3.0 Portable',
    description: 'Disque dur externe portable 2To avec alimentation par USB pour sauvegarde et stockage.',
    category: 'storage',
    price: 54.99,
    originalPrice: 99.99,
    discount: 45,
    rating: 4.6,
    reviews: 4523,
    image: 'https://via.placeholder.com/400x300/14b8a6/ffffff?text=HDD+2TB',
    images: [
      'https://via.placeholder.com/400x300/14b8a6/ffffff?text=HDD+2TB',
    ],
    stock: 145,
    aliexpressUrl: '#',
    features: [
      'Capacité 2To',
      'USB 3.0 haute vitesse',
      'Alimenté par USB',
      'Format portable 2.5"',
      'Plug and play',
      'Garantie 2 ans',
    ],
    specifications: {
      'Capacité': '2To',
      'Interface': 'USB 3.0',
      'Vitesse': 'Jusqu\'à 120 MB/s',
      'Format': '2.5 pouces',
      'Alimentation': 'Bus USB',
      'Dimensions': '115 x 80 x 14 mm',
      'Poids': '180g',
    },
  },

  // AUDIO - 3 produits
  {
    id: 'headset-1',
    name: 'Casque Gaming RGB 7.1 Surround Sans Fil',
    description: 'Casque gaming professionnel avec son surround 7.1, micro antibruit et batterie 30h.',
    category: 'audio',
    price: 59.99,
    originalPrice: 129.99,
    discount: 54,
    rating: 4.8,
    reviews: 4762,
    image: 'https://via.placeholder.com/400x300/a855f7/ffffff?text=Gaming+Headset',
    images: [
      'https://via.placeholder.com/400x300/a855f7/ffffff?text=Gaming+Headset',
    ],
    stock: 98,
    aliexpressUrl: '#',
    features: [
      'Son surround virtuel 7.1',
      'Sans fil 2.4GHz',
      'Micro antibruit détachable',
      'RGB personnalisable',
      'Batterie 30 heures',
      'Coussinets mousse mémoire',
    ],
    specifications: {
      'Type': 'Gaming sans fil',
      'Surround': '7.1 virtuel',
      'Connexion': '2.4GHz + USB Type-C',
      'Batterie': '30 heures',
      'Drivers': '50mm néodyme',
      'Micro': 'Unidirectionnel détachable',
      'Poids': '320g',
    },
  },
  {
    id: 'earbuds-1',
    name: 'Écouteurs Bluetooth 5.3 True Wireless ANC',
    description: 'Écouteurs sans fil avec réduction de bruit active, son Hi-Fi et étui de charge sans fil.',
    category: 'audio',
    price: 34.99,
    originalPrice: 89.99,
    discount: 61,
    rating: 4.7,
    reviews: 8234,
    image: 'https://via.placeholder.com/400x300/22c55e/ffffff?text=TWS+Earbuds',
    images: [
      'https://via.placeholder.com/400x300/22c55e/ffffff?text=TWS+Earbuds',
    ],
    stock: 267,
    aliexpressUrl: '#',
    features: [
      'Bluetooth 5.3',
      'ANC réduction bruit',
      'Son Hi-Fi AAC',
      'Charge sans fil Qi',
      'IPX7 résistant à l\'eau',
      'Autonomie 32h avec étui',
    ],
    specifications: {
      'Bluetooth': '5.3',
      'ANC': 'Réduction active 35dB',
      'Drivers': '13mm graphène',
      'Autonomie': '8h + 24h (étui)',
      'Charge': 'Sans fil Qi + USB-C',
      'Étanchéité': 'IPX7',
      'Poids': '4g (écouteur)',
    },
  },
  {
    id: 'speaker-1',
    name: 'Enceinte Bluetooth Portable 40W Étanche',
    description: 'Enceinte puissante avec basses profondes, LED RGB et batterie longue durée pour l\'extérieur.',
    category: 'audio',
    price: 44.99,
    originalPrice: 99.99,
    discount: 55,
    rating: 4.6,
    reviews: 3456,
    image: 'https://via.placeholder.com/400x300/f97316/ffffff?text=BT+Speaker',
    images: [
      'https://via.placeholder.com/400x300/f97316/ffffff?text=BT+Speaker',
    ],
    stock: 124,
    aliexpressUrl: '#',
    features: [
      'Puissance 40W',
      'Bluetooth 5.0',
      'IPX7 étanche',
      'LED RGB',
      'Batterie 15 heures',
      'Entrée AUX et microSD',
    ],
    specifications: {
      'Puissance': '40W RMS',
      'Bluetooth': '5.0',
      'Batterie': '6000mAh (15h)',
      'Étanchéité': 'IPX7',
      'Drivers': '2 x 20W',
      'Portée': '30 mètres',
      'Poids': '850g',
    },
  },

  // MONITORS - 3 produits
  {
    id: 'monitor-1',
    name: 'Écran Gaming 27" 165Hz QHD Incurvé',
    description: 'Moniteur gaming incurvé 1500R avec dalle 165Hz pour une immersion totale et fluidité maximale.',
    category: 'monitors',
    price: 229.99,
    originalPrice: 399.99,
    discount: 42,
    rating: 4.8,
    reviews: 1847,
    image: 'https://via.placeholder.com/400x300/3b82f6/ffffff?text=27+Gaming',
    images: [
      'https://via.placeholder.com/400x300/3b82f6/ffffff?text=27+Gaming',
    ],
    stock: 45,
    aliexpressUrl: '#',
    features: [
      'Dalle 27" QHD 2560x1440',
      'Taux rafraîchissement 165Hz',
      'Temps réponse 1ms',
      'Incurvé 1500R',
      'FreeSync Premium',
      'HDR10',
    ],
    specifications: {
      'Taille': '27 pouces',
      'Résolution': '2560 x 1440 (QHD)',
      'Fréquence': '165Hz',
      'Temps réponse': '1ms MPRT',
      'Dalle': 'VA incurvée 1500R',
      'Connectique': 'HDMI 2.0 x2, DP 1.4',
      'Support': 'VESA 100x100',
    },
  },
  {
    id: 'monitor-2',
    name: 'Moniteur 24" Full HD IPS Pivotant',
    description: 'Écran professionnel 24" avec dalle IPS, pivot et réglage hauteur pour productivité optimale.',
    category: 'monitors',
    price: 129.99,
    originalPrice: 219.99,
    discount: 41,
    rating: 4.7,
    reviews: 2341,
    image: 'https://via.placeholder.com/400x300/059669/ffffff?text=24+IPS',
    images: [
      'https://via.placeholder.com/400x300/059669/ffffff?text=24+IPS',
    ],
    stock: 78,
    aliexpressUrl: '#',
    features: [
      'Dalle IPS 24" Full HD',
      'Angles vision 178°',
      'Pivot portrait/paysage',
      'Réglage hauteur',
      'Mode anti-fatigue',
      'Haut-parleurs intégrés',
    ],
    specifications: {
      'Taille': '24 pouces',
      'Résolution': '1920 x 1080 (FHD)',
      'Dalle': 'IPS',
      'Fréquence': '75Hz',
      'Luminosité': '250 cd/m²',
      'Contraste': '1000:1',
      'Connectique': 'HDMI, VGA, Audio',
    },
  },
  {
    id: 'monitor-3',
    name: 'Écran Portable 15.6" 4K USB-C Tactile',
    description: 'Moniteur portable tactile ultra fin avec USB-C pour double écran nomade.',
    category: 'monitors',
    price: 179.99,
    originalPrice: 299.99,
    discount: 40,
    rating: 4.6,
    reviews: 1523,
    image: 'https://via.placeholder.com/400x300/8b5cf6/ffffff?text=Portable+4K',
    images: [
      'https://via.placeholder.com/400x300/8b5cf6/ffffff?text=Portable+4K',
    ],
    stock: 56,
    aliexpressUrl: '#',
    features: [
      'Écran 15.6" 4K tactile',
      'Alimenté par USB-C',
      'Ultra fin 4mm',
      'Étui support magnétique',
      'HDR',
      'Compatible tous appareils',
    ],
    specifications: {
      'Taille': '15.6 pouces',
      'Résolution': '3840 x 2160 (4K)',
      'Tactile': 'Oui, 10 points',
      'Luminosité': '300 cd/m²',
      'Connexion': 'USB-C x2, mini HDMI',
      'Épaisseur': '4mm',
      'Poids': '700g',
    },
  },

  // NETWORKING - 3 produits
  {
    id: 'router-1',
    name: 'Routeur WiFi 6 AX3000 Dual Band Gigabit',
    description: 'Routeur WiFi 6 nouvelle génération avec 4 antennes pour couverture maximale et vitesses élevées.',
    category: 'networking',
    price: 69.99,
    originalPrice: 149.99,
    discount: 53,
    rating: 4.7,
    reviews: 2134,
    image: 'https://via.placeholder.com/400x300/dc2626/ffffff?text=WiFi+6+Router',
    images: [
      'https://via.placeholder.com/400x300/dc2626/ffffff?text=WiFi+6+Router',
    ],
    stock: 89,
    aliexpressUrl: '#',
    features: [
      'WiFi 6 (802.11ax)',
      'Vitesse jusqu\'à 3000 Mbps',
      'Dual Band 2.4GHz + 5GHz',
      '4 antennes externes',
      'MU-MIMO et OFDMA',
      '4 ports Gigabit LAN',
    ],
    specifications: {
      'Standard': 'WiFi 6 (802.11ax)',
      'Vitesse': '574 Mbps (2.4GHz) + 2402 Mbps (5GHz)',
      'Ports': '4 x Gigabit LAN, 1 x Gigabit WAN',
      'Antennes': '4 externes',
      'CPU': 'Dual-core 1.5GHz',
      'Mémoire': '512MB RAM',
      'Couverture': 'Jusqu\'à 200m²',
    },
  },
  {
    id: 'adapter-1',
    name: 'Adaptateur WiFi USB 3.0 AC1300 Dual Band',
    description: 'Clé WiFi USB haute performance avec antenne externe pour améliorer la réception sans fil.',
    category: 'networking',
    price: 15.99,
    originalPrice: 39.99,
    discount: 60,
    rating: 4.6,
    reviews: 5234,
    image: 'https://via.placeholder.com/400x300/f59e0b/ffffff?text=WiFi+Adapter',
    images: [
      'https://via.placeholder.com/400x300/f59e0b/ffffff?text=WiFi+Adapter',
    ],
    stock: 234,
    aliexpressUrl: '#',
    features: [
      'AC1300 Dual Band',
      'USB 3.0 ultra rapide',
      'Antenne externe 5dBi',
      'Compatible WiFi 6',
      'Driver-free Windows 10/11',
      'Mode AP et STA',
    ],
    specifications: {
      'Standard': '802.11ac Wave 2',
      'Vitesse': '400 Mbps (2.4GHz) + 867 Mbps (5GHz)',
      'Interface': 'USB 3.0',
      'Antenne': '5dBi externe',
      'Chipset': 'Realtek 8812BU',
      'Compatibilité': 'Windows/Mac/Linux',
    },
  },
  {
    id: 'switch-1',
    name: 'Switch Réseau Gigabit 8 Ports Non Géré',
    description: 'Switch réseau 8 ports Gigabit plug-and-play pour étendre votre réseau local.',
    category: 'networking',
    price: 24.99,
    originalPrice: 59.99,
    discount: 58,
    rating: 4.7,
    reviews: 3124,
    image: 'https://via.placeholder.com/400x300/06b6d4/ffffff?text=8+Port+Switch',
    images: [
      'https://via.placeholder.com/400x300/06b6d4/ffffff?text=8+Port+Switch',
    ],
    stock: 167,
    aliexpressUrl: '#',
    features: [
      '8 ports Gigabit',
      'Plug and play',
      'Boîtier métal',
      'IEEE 802.3az',
      'Auto-MDI/MDIX',
      'LED par port',
    ],
    specifications: {
      'Ports': '8 x 10/100/1000 Mbps',
      'Débit': '16 Gbps',
      'Buffer': '1.5Mb',
      'Norme': 'IEEE 802.3/3u/3ab',
      'Consommation': 'Économie énergie',
      'Dimensions': '158 x 101 x 25 mm',
    },
  },
];

export function getProducts(): Product[] {
  return products;
}

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter(p => p.category === category);
}

export function getCategories(): Category[] {
  return categories;
}
