#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║          💰 ANALYSE DES BÉNÉFICES - TECHSHOP                          ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📊 BÉNÉFICES PAR CATÉGORIE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💻 LAPTOPS (3 produits)"
echo "   • PC Portable i7 16Go      : 114.99€  (21% marge)"
echo "   • Laptop Gaming Ryzen 7    : 189.99€  (21% marge)"  
echo "   • Ultrabook i5 8Go         :  79.99€  (20% marge)"
echo "   └─ Total catégorie         : 384.97€"
echo ""
echo "⌨️  ACCESSOIRES PC (3 produits)"
echo "   • Clavier RGB Gaming       :  16.39€  (36% marge)"
echo "   • Souris Gaming 16000 DPI  :  11.99€  (40% marge) ⭐"
echo "   • Webcam 4K                :  13.99€  (35% marge)"
echo "   └─ Total catégorie         :  42.37€"
echo ""
echo "💾 STOCKAGE (3 produits)"
echo "   • SSD NVMe 1To             :  23.99€  (30% marge)"
echo "   • Clé USB 256Go            :   7.99€  (40% marge) ⭐"
echo "   • Disque Dur 2To           :  17.49€  (32% marge)"
echo "   └─ Total catégorie         :  49.47€"
echo ""
echo "🎧 AUDIO (3 produits)"
echo "   • Casque Gaming 7.1        :  18.99€  (32% marge)"
echo "   • Écouteurs Bluetooth ANC  :  13.49€  (39% marge) ⭐"
echo "   • Enceinte Bluetooth 40W   :  15.49€  (34% marge)"
echo "   └─ Total catégorie         :  47.97€"
echo ""
echo "🖥️  ÉCRANS (3 produits)"
echo "   • Écran Gaming 27\" 165Hz   :  51.99€  (23% marge)"
echo "   • Moniteur 24\" IPS         :  31.99€  (25% marge)"
echo "   • Écran Portable 15.6\" 4K  :  41.99€  (23% marge)"
echo "   └─ Total catégorie         : 125.97€"
echo ""
echo "📡 RÉSEAU (3 produits)"
echo "   • Routeur WiFi 6           :  20.99€  (30% marge)"
echo "   • Adaptateur WiFi USB      :   6.39€  (40% marge) ⭐"
echo "   • Switch 8 Ports           :   9.49€  (38% marge)"
echo "   └─ Total catégorie         :  36.87€"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📈 RÉSUMÉ GLOBAL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   🎯 Bénéfice TOTAL (18 produits)    : 687.62€"
echo "   📊 Bénéfice MOYEN par article      :  38.20€"
echo "   💎 Marge moyenne                   :  29%"
echo ""
echo "   🏆 Meilleur bénéfice €             : Laptop Gaming (189.99€)"
echo "   ⭐ Meilleure marge %               : Souris + Clé USB + WiFi (40%)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 PROJECTIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Si vous vendez 1 de chaque (18 articles)"
echo "   • Chiffre d'affaires    : 2,754.68€"
echo "   • Bénéfice net          :   687.62€"
echo ""
echo "   Si vous vendez 10 de chaque par mois"
echo "   • CA mensuel            : 27,546.80€"
echo "   • Bénéfice mensuel      :  6,876.20€"
echo "   • Bénéfice annuel       : 82,514.40€"
echo ""
echo "   Si vous vendez 50 de chaque par mois"
echo "   • CA mensuel            : 137,734€"
echo "   • Bénéfice mensuel      :  34,381€"
echo "   • Bénéfice annuel       : 412,572€"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📄 Voir l'analyse complète dans: ANALYSE_BENEFICES.md"
echo ""
